config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  resources :users, only: %i[new create]
  resources :bookstores, only: %i[index show new edit create update destroy] do
    resources :store_reviews, only: %i[show new  edit create update destroy], shallow: true
    collection do
      get :wanna_go_bookstores
    end
  end

  resource :profiles, only: %i[show edit update] do
    get "bookstore_list", to: "profiles#bookstore_list"
    get "review_list", to: "profiles#review_list"
    resources :purchase_histories, only: %i[create edit update destroy]
  end
  resources :wanna_go_bookstores, only: %i[create destroy]
  resources :password_resets, only: %i[new edit create update]
  resources :questions, only: %i[index create] do
    collection do
      get :result
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'how_to_use', to: 'pages#how_to_use'
  get 'inquiry', to: 'pages#inquiry'
  get 'select_login', to: 'pages#select_login'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy_policy', to: 'pages#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/provider', to: 'oauths#oauth', as: :auth_at_provider
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
  validates :title, presence: true
  validates :note, length: { maximum: 255 }

  belongs_to :user
  belongs_to :store_review
end

app/controllers/purchase_histories_controller.rb
class PurchaseHistoriesController < ApplicationController
  before_action :set_purchase_history, only: %i[edit update destroy]

  def edit
    add_breadcrumb 'HOME', :root_path
    add_breadcrumb t('profiles.show.review_list'), :review_list_profiles_path
    add_breadcrumb t('.title')
  end

  def create
    @purchase_history = current_user.purchase_histories.build(purchase_history_params)
    if @purchase_history.save
      redirect_to review_list_profiles_path(purchase_history_id: @purchase_history.store_review_id),
                  success: t('.success')
    else
      @store_reviews = current_user.store_reviews.includes(:user).order(created_at: :desc).page(params[:page]).per(9)
      @purchase_histories = current_user.purchase_histories.includes(:user).order(created_at: :desc)
                                        .page(params[:page]).per(9)
      flash.now[:danger] = t('.failure')
      render 'profiles/review_list', status: :unprocessable_entity
    end
  end

  def update
    if @purchase_history.update(purchase_history_params)
      redirect_to review_list_profiles_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @purchase_history.destroy!
    redirect_to review_list_profiles_path, success: t('.success')
  end

  private

  def set_purchase_history
    @purchase_history = current_user.purchase_histories.find(params[:id])
  end

  def purchase_history_params
    params.require(:purchase_history).permit(:purchase_date, :title, :author_name, :note, :store_review_id)
  end
end

app/views/purchase_histories/_form.html.erb
<%= form_with(model: @purchase_history, url: @purchase_history.persisted? ? profiles_purchase_history_path(@purchase_history) : profiles_purchase_histories_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :purchase_date %>
  <%= f.text_field :purchase_date, placeholder: "半角 例 2024-06-29" %>

  本屋の名前
  <%= f.collection_select :store_review_id, current_user.store_reviews, :id, :bookstore_name, prompt: "購入した推し本屋を選択してください" %>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control", placeholder: "入力してください" %>
  
  <%= f.label :author_name %>
  <%= f.text_field :author_name, class: "form-control", placeholder: "入力してください" %>
  </div>
  <%= f.label :note %>
  <%= f.text_area :note, class: "form-control", placeholder: "入力してください、改行可能です" %>

  <%= f.submit nil, class: "btn btn-success" %>
<% end %>

app/views/purchase_histories/_purchase_history.html.erb
<div id="purchase_history-id-<%= purchase_history.id %>" class="border mb-3">
  <div class="text-end">
  <%= link_to edit_profiles_purchase_history_path(purchase_history), id: "button-edit-#{purchase_history}" do %>
    <i class="bi bi-pencil"></i>
  <% end %>
  <%= link_to profiles_purchase_history_path(purchase_history), data: { turbo_method: :delete, turbo_confirm: :"削除しますか？" }, id: "button-delete-#{purchase_history}" do %>
    <i class="bi bi-trash"></i>
  <% end %>
  </div>
  <%= purchase_history.purchase_date %>
  
<p><%= purchase_history.store_review.bookstore.name %></p>
<div>
<p><%= purchase_history.title %></p>
<p><%= purchase_history.author_name %></p>
</div>
<div>
<%= simple_format(purchase_history.note) %>
</div>
</div>

app/views/purchase_histories/edit.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
<div class="col-sm-12 col-lg-6 offset-6">
<h3>推し活リストの編集</h3>
    <%= render "purchase_histories/form"%>
</div>
</div>