config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  resources :users, only: %i[new create]
  resources :bookstores, only: %i[index show new edit create update destroy] do
    resources :store_reviews, only: %i[show new  edit create update destroy], shallow: true
    collection do
      get :wanna_go_bookstores
    end
  end

  resource :profiles, only: %i[show edit update] do
    get "bookstore_list", to: "profiles#bookstore_list"
    get "review_list", to: "profiles#review_list"
    resources :purchase_histories, only: %i[create edit update destroy]
  end
  resources :wanna_go_bookstores, only: %i[create destroy]
  resources :password_resets, only: %i[new edit create update]
  resources :questions, only: %i[index create] do
    collection do
      get :result
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'how_to_use', to: 'pages#how_to_use'
  get 'inquiry', to: 'pages#inquiry'
  get 'select_login', to: 'pages#select_login'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy_policy', to: 'pages#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/provider', to: 'oauths#oauth', as: :auth_at_provider
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'header_logo.png' %>
  <% end %>

  <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>
    
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto main-nav align-items-center">
    <li class="nav-item">
      <%= link_to t('header.find_bookstore'), bookstores_path, class: 'nav-link' %>
    </li>
    <li class="nav-item" data-turbo="false">
    <%= link_to t('header.diagnostic'), questions_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
    <%= link_to t('header.how_to_use'), "/how_to_use", class: 'nav-link', target: :_blank, rel: "noopener noreferrer" %>
    </li>
    <li class="nav-item">
    <%= link_to t('header.login'), "/select_login", class: 'nav-link' %>  
    </li>
    </ul>
  </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

<button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav main-nav align-items-center">

    <li class="nav-item">
    <%= link_to t('footer.terms_of_service'), "/terms_of_service", class: "nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to t('footer.inquiry'), "/inquiry", class: "nav-link" %>
    </li>
    <li class="nav-item">
    <%= link_to t('footer.privacy_policy'), "/privacy_policy", class: "nav-link" %>
    </li>
  </ul>
  </div>
  <div class="copyright">
    <p>©️2024. ほんやがたり</p>
  </div>
</nav>

</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'header_logo.png' %>
    <% end %>

    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto main-nav align-items-center">
    <li class="nav-item">
      <%= link_to t('header.find_bookstore'), bookstores_path, class: 'nav-link' %>
    </li>
    <li class="nav-item" data-turbo="false">
    <%= link_to t('header.diagnostic'), questions_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
    <%= link_to t('header.how_to_use'), "/how_to_use", class: 'nav-link', target: :_blank, rel: "noopener noreferrer" %>
    </li>

    <li class="nav-item dropdown dropdown-slide">
      <%= link_to "#{current_user.name}", "#", class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown'}, aria: { haspopop: 'true', expand: 'false' }, id: 'header-board-menu' %>
     <div class="dropdown-menu dropdown-menu-end">
       <%= link_to t('header.profile'), profiles_path, class: 'dropdown-item' %>
       <%= link_to t('header.wanna_go_bookstore'), "/profiles/bookstore_list", class: 'dropdown-item' %>
       <%= link_to t('header.review_list'), review_list_profiles_path, class: 'dropdown-item' %>
     <div class="dropdown-divider"></div>
       <%= link_to t('header.logout'), logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
     </div>
    </li>
    </ul>
  </div>
  </nav>
</header>