config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  resources :users, only: %i[new create]
  resources :bookstores, only: %i[index show new edit create update destroy] do
    resources :store_reviews, only: %i[show new  edit create update destroy], shallow: true
    collection do
      get :wanna_go_bookstores
    end
  end

  resource :profiles, only: %i[show edit update] do
    get "bookstore_list", to: "profiles#bookstore_list"
    get "review_list", to: "profiles#review_list"
    resources :purchase_histories, only: %i[create edit update destroy]
  end
  resources :wanna_go_bookstores, only: %i[create destroy]
  resources :password_resets, only: %i[new edit create update]
  resources :questions, only: %i[index create] do
    collection do
      get :result
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  get 'how_to_use', to: 'pages#how_to_use'
  get 'inquiry', to: 'pages#inquiry'
  get 'select_login', to: 'pages#select_login'
  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy_policy', to: 'pages#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post 'oauth/callback', to: 'oauths#callback'
  get 'oauth/callback', to: 'oauths#callback'
  get 'oauth/provider', to: 'oauths#oauth', as: :auth_at_provider
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bookstore.rb
class Bookstore < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates :name, presence: true, length: { maximum: 255 }
  validates :address, presence: true, length: { maximum: 255 }

  belongs_to :user
  has_many :store_reviews, dependent: :destroy
  has_many :tag_relations, dependent: :destroy
  has_many :tags, through: :tag_relations
  has_many :wanna_go_bookstores, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[name address]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  scope :tag_join, ->(tag_name) { joins(:tags).where(tags: { name: tag_name }) }
end

app/controllers/bookstores_controller.rb
class BookstoresController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_bookstore, only: %i[edit update destroy]

  add_breadcrumb 'HOME', :root_path

  def index
    add_breadcrumb t('.title'), :bookstores_path
    @q = Bookstore.ransack(params[:q])
    @bookstores = if params[:tag_name]
                    @q.result(distinct: true).includes(:user).order(created_at: :desc).tag_join(params[:tag_name])
                      .page(params[:page])
                  else
                    @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
                  end
  end

  def show
    @bookstore = Bookstore.find(params[:id])
    add_breadcrumb t('.index.title'), :bookstores_path
    add_breadcrumb @bookstore.name, :bookstore_path
    @store_reviews = @bookstore.store_reviews.order(created_at: :desc)
    gon.bookstore_lat = @bookstore.latitude
    gon.bookstore_lng = @bookstore.longitude
  end

  def new
    add_breadcrumb t('.index.title'), :bookstores_path
    add_breadcrumb t('.title')
    @bookstore = Bookstore.new
  end

  def edit
    add_breadcrumb t('.index.title'), :bookstores_path
    add_breadcrumb @bookstore.name, :bookstore_path
    add_breadcrumb t('.title')
  end

  def create
    @bookstore = current_user.bookstores.build(bookstore_params)
    if @bookstore.save
      redirect_to bookstores_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bookstore.update(bookstore_params)
      redirect_to bookstore_path(@bookstore), success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bookstore.destroy!
    redirect_to bookstores_path, success: t('.success'), status: :see_other
  end

  private

  def bookstore_params
    params.require(:bookstore).permit(:name, :address, tag_ids: [])
  end

  def set_bookstore
    @bookstore = Bookstore.find(params[:id])
  end
end

app/views/bookstores/_already_go.html.erb
<%= link_to wanna_go_bookstore_path(current_user.wanna_go_bookstores.find_by(bookstore_id: bookstore.id)), id: "already_go-button-for-bookstore-#{bookstore.id}", data: { turbo_method: :delete } do %>
  <i class="bi bi-bookmark-fill"></i>
<% end %>

app/views/bookstores/_bookstore.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="bookstore-id-<%= bookstore.id %>">
    <div class="card"> 
      <div class="card-header">
        書店情報No.<%= bookstore.id %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= bookstore.name %></h5>
        <p class="card-text"><%= bookstore.address %></p>
        <div data-turbo="false">
        <%= link_to t('bookstores.index.to_show_bookstore'), bookstore_path(bookstore), class: "btn btn-success" %> 
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookstores/_form.html.erb
<%= form_with(model: bookstore, local: true) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="mb-3">
      <%= f.label :name, class: "form-label" %>
      <%= f.text_field :name, id: "Name", class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :address, class: "form-label" %>
      <%= f.text_field :address, id: "Address", class: "form-control" %>
    </div>
    
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=places&callback=initialize"></script>

    <div class="mb-3">
      <p>この本屋さんに当てはまるものを選んでください（複数選択可）</p>
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name, {}, { multiple: true, name: "bookstore[tag_ids][]" } %>
    </div>
    <div data-turbo="false">
    <%= f.submit nil, class: "btn btn-success" %>
    </div>
    <% end %>

app/views/bookstores/_search.html.erb
<%= search_form_for q, url: url do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :address_or_name_cont, placeholder: "店舗名・地名で絞り込めます", class: "form-control" %>
  <div class="input-group-append">
    <%= f.submit nil, class: "btn btn-success" %>
  </div>
  </div>
<% end %>

app/views/bookstores/_wanna_go.html.erb
<%= link_to wanna_go_bookstores_path(bookstore_id: bookstore.id), id: "wanna_go-button-for-bookstore-#{bookstore.id}", data: { turbo_method: :post } do %>
  <i class="bi bi-bookmark"></i>
<% end %>

app/views/bookstores/_wanna_go_button.html.erb
<% if current_user.wanna_go?(@bookstore) %>
  <%= render "bookstores/already_go", { bookstore: @bookstore } %>
<% else %>
  <%= render "bookstores/wanna_go", { bookstore: @bookstore } %>
<% end %>

app/views/bookstores/edit.html.erb
<%= content_for(:title, t('.title')) %>
<div class="container">
  <div class="col-lg-8 offset-lg-1">
    <h1><%= t('.title') %></h1>
    <%= render "form", { bookstore: @bookstore} %>
  </div>
</div>

app/views/bookstores/index.html.erb
<%= content_for(:title, t('.title')) %>

<div class="container">
<h1><%= t('.title') %></h1>
  <div>
    <%= render "search", q: @q, url: bookstores_path %>
  </div>
  <div class="row">
    <% if @bookstores.present? %>
      <%= render @bookstores %>
    <% else %>
      <div class="mb-3">書店情報がありません</div>
    <% end %>
  </div>
  <%= paginate @bookstores, theme: 'bootstrap-5' %>
  <div data-turbo="false" class="text-center">
      <%= link_to t('.to_create_bookstore'), new_bookstore_path, class: "btn btn-success" %>
    </div>
</div>

app/views/bookstores/new.html.erb
<%= content_for(:title, t('.title')) %>
<div class="container">
  <div class="col-lg-8 offset-lg-1">
    <h1><%= t('.title') %></h1>
    <%= render "form", { bookstore: @bookstore } %>
  </div>
</div>

app/views/bookstores/show.html.erb
<%= content_for(:title, @bookstore.name) %>
<div class="container">
  <h1><%= t('.title') %></h1>
  <div class="d-flex">
  <h3><%= @bookstore.name %></h3>
    <% if logged_in? %>
    <%= render "bookstores/wanna_go_button", bookstore: @bookstore  %>
    <div data-turbo="false">
    <%= link_to edit_bookstore_path(@bookstore), class: "button-edit-#{@bookstore.id}" do %>
      <i class="bi bi-pencil"></i>
    <% end %>
    </div>
    <% end %>
    <% if current_user && current_user.own?(@bookstore) %>
    <%= link_to bookstore_path(@bookstore), class: "button-delete-#{@bookstore.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.flash_message.delete') } do %>
      <i class="bi bi-trash"></i>
    <% end %>
    <% end %>
  </div>

  <div class="mb-2">
    場所：<%= @bookstore.address %>
  </div>
  <div class="mb-2">
    タグ：<% @bookstore.tags.each do |tag| %>
      <%= link_to bookstores_path(tag_name: tag.name), class: "badge rounded-pill bg-success text-decoration-none text-white" do %>
        <%= tag.name %>
      <% end %>
    <% end %>
  </div>

  <div id="map" style="height: 250px; width: 30%;"></div>

  <script>
  (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
    key: '<%= ENV['GOOGLE_MAPS_API_KEY'] %>',
    // Add other bootstrap parameters as needed, using camel case.
    // Use the 'v' parameter to indicate the version to load (alpha, beta, weekly, etc.)
  });
  </script>

  <div class="row">
    <h3>この本屋のおすすめ文</h3>
    <% if @store_reviews.present? %>
    <%= render @store_reviews %>
    <% else %>
    <div class="mb-3">まだおすすめ文がありません</div>
    <% end %>
    </div>

  <div>
  <%= link_to "この本屋のおすすめ文を書いてみる", new_bookstore_store_review_path(@bookstore), class: "btn btn-success mb-2" %>
  </div>
  <%= link_to "本屋一覧へ", bookstores_path, class: "btn btn-success mb-2" %>
</div>
</div>